import { BaseModel } from "@/app/base/models/base.model";

export interface FieldElementItem {
    Type: string;
    Name: string;
    Label: string;
    ShowLabel: boolean;
    Value: any;
    Visible: boolean;
    ShowIcon: boolean;
    CustomIcon: string;
    ShowCustomIcon: boolean;
    FormatValue: string;
    MinValue: any;
    MaxValue: any;
    ReadOnly: boolean;
    Disabled: boolean;
    TimeOnly: boolean;
    ShowTime: boolean;
    HourFormat: any;
    Required: boolean;
    Severity: string;
    Loading: boolean;
    MinFractionDigits: any;
    MaxFractionDigits: any;
    ShowPrefix: boolean;
    Prefix: string;
    ShowSuffix: boolean;
    Suffix: string;
    Currency: any;
    Locale: any;
    PlaceHolder: any;
    HelpText: any;
    OptionValue: any;
    OptionLabel: any;
    MaxSelectValue: any;
    OptionName: any;
    Variant: any;
    IconPosition: any;
    Raised: boolean;


    CharacterCasing: string;
    InputClass: string;
    ColSpanClass: string;
    AlignmentXClass: string;
    AlignmentYClass: string;
    RequiredMessage: string;
    Icon: string;
    IconColor: string;
    LabelStyle: string;
    ResourceUrl: string;
    BodyResourceUrl: any;
    Fields: Array<FieldElementItem>;
    GridVisible: boolean;
    RefId: string;
    Action: string;
    Class: string;
    DecimalPlaces: number;
    ThousandsSeparator: boolean;
}

export class FieldElementItem extends BaseModel {
    Type: string;
    Name: string;
    Label: string;
    ShowLabel: boolean;
    Value: any;
    Visible: boolean;
    ShowIcon: boolean;
    CustomIcon: string;
    ShowCustomIcon: boolean;
    FormatValue: string;
    MinValue: any;
    MaxValue: any;
    ReadOnly: boolean;
    Disabled: boolean;
    TimeOnly: boolean;
    ShowTime: boolean;
    HourFormat: any;
    Required: boolean;
    Severity: string;
    Loading: boolean;
    MinFractionDigits: any;
    MaxFractionDigits: any;
    ShowPrefix: boolean;
    Prefix: string;
    ShowSuffix: boolean;
    Suffix: string;
    Currency: any;
    Locale: any;
    PlaceHolder: any;
    HelpText: any;
    OptionValue: any;
    OptionLabel: any;
    MaxSelectValue: any;
    OptionName: any;
    Variant: any;
    IconPosition: any;
    Raised: boolean;

    CharacterCasing: string;
    InputClass: string;
    ColSpanClass: string;
    AlignmentXClass: string;
    AlignmentYClass: string;
    RequiredMessage: string;
    Icon: string;
    IconColor: string;
    LabelStyle: string;
    ResourceUrl: string;
    BodyResourceUrl: any;
    Fields: Array<FieldElementItem>;
    GridVisible: boolean;
    RefId: string;
    Action: string;
    Class: string;
    DecimalPlaces: number;
    ThousandsSeparator: boolean;

    constructor(data: Partial<FieldElementItem>) {
        super(data);
        this.Type = data.Type || 'text';
        this.Name = data.Name || '';
        this.Label = data.Label || '';
        this.ShowLabel = data.ShowLabel || false;
        this.Value = data.Value || undefined;
        this.Visible = data.Visible !== undefined ? data.Visible : false;
        this.ShowIcon = data.ShowIcon || false;
        this.CustomIcon = data.CustomIcon || '';
        this.ShowCustomIcon = data.ShowCustomIcon || false;
        this.FormatValue = data.FormatValue || '';
        this.MinValue = data.MinValue || undefined;
        this.MaxValue = data.MaxValue || undefined;
        this.ReadOnly = data.ReadOnly !== undefined ? data.ReadOnly : false;
        this.Disabled = data.Disabled !== undefined ? data.Disabled : false;
        this.TimeOnly = data.TimeOnly !== undefined ? data.TimeOnly : false;
        this.ShowTime = data.ShowTime !== undefined ? data.ShowTime : false;
        this.HourFormat = data.HourFormat !== undefined ? data.HourFormat : '24';
        this.Required = data.Required !== undefined ? data.Required : false;
        this.Severity = data.Severity || 'primary';
        this.Loading = data.Loading !== undefined ? data.Loading : false;
        this.MinFractionDigits = data.MinFractionDigits !== undefined ? data.MinFractionDigits : undefined;
        this.MaxFractionDigits = data.MaxFractionDigits !== undefined ? data.MaxFractionDigits : undefined;
        this.ShowPrefix = data.ShowPrefix !== undefined ? data.ShowPrefix : false;
        this.Prefix = data.Prefix || '';
        this.ShowSuffix = data.ShowSuffix !== undefined ? data.ShowSuffix : false;
        this.Suffix = data.Suffix || '';
        this.Currency = data.Currency || undefined;
        this.Locale = data.Locale || undefined;
        this.PlaceHolder = data.PlaceHolder || undefined;
        this.OptionValue = data.OptionValue || undefined;
        this.OptionLabel = data.OptionLabel || undefined;
        this.MaxSelectValue = data.MaxSelectValue || undefined;
        this.OptionName = data.OptionName || undefined;
        this.Variant = data.Variant || undefined;
        this.IconPosition = data.IconPosition || undefined;
        this.Raised = data.Raised || false;


        this.CharacterCasing = data.CharacterCasing || 'normal';
        this.InputClass = data.InputClass || '';
        this.ColSpanClass = data.ColSpanClass || '';
        this.AlignmentXClass = data.AlignmentXClass || '';
        this.AlignmentYClass = data.AlignmentYClass || '';
        this.RequiredMessage = data.RequiredMessage || '';
        this.Icon = data.Icon || 'fa-solid fa-ban';
        this.IconColor = data.IconColor || 'text-slate-600';
        this.LabelStyle = data.LabelStyle || 'text-slate-600';
        this.ResourceUrl = data.ResourceUrl || '';
        this.BodyResourceUrl = data.ResourceUrl || null;
        this.Fields = data.Fields || [];
        this.GridVisible = data.GridVisible || false;
        this.RefId = data.RefId || '';
        this.Action = data.Action || '';
        this.Class = data.Class || '';
        this.DecimalPlaces = data.DecimalPlaces || 0;
        this.ThousandsSeparator = data.ThousandsSeparator || false;
    }
}
